#!bin/bash

sxhkd -c $HOME/.config/berry/sxhkdrc &
picom &
feh --bg-scale ~/wallpapers/triangles.jpg

# Setting Colors
berryc focus_color 98c379
berryc inner_focus_color 98c379
berryc inner_unfocus_color 282c34
berryc text_focus_color 000000
berryc text_unfocus_color abb2bf
# Font
berryc set_font jetbrains-mono-12
# Tweaking size
berryc title_height 40
# Misc
berryc draw_text "true"
berryc edge_lock "true"
berryc edge_gap 10 10 10 10
